[project]
name = "pantone"
version = "0.2.0"
description = "Drives parcans with colors derived from motion sensors."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.15",
    "netifaces>=0.11.0",
]
